"""Seed realistic Bay Area demo data spanning the last 40 days across Tech, Work, and Family."""

import asyncio
import json
import os
from datetime import datetime

import agents
import db

DEMO_THOUGHTS = [
    {
        "created_at": "2026-07-14T07:45:00Z",
        "transcript": "Why do all AI memory systems assume memory is just a vector database of documents? Real human memory is episodic and tied to emotional state and location. If we want personal agents to actually understand us over months, we need to capture what we're actively thinking out loud during walks, not just our email inbox.",
        "summary": "Reflections on why existing AI memory architectures fail by ignoring episodic, human-curated streams of consciousness.",
        "topics": ["AI agents", "episodic memory", "cognitive architecture", "long-horizon"],
        "entities": ["Vector DBs", "Personal Agents"],
        "mood": "inspired",
        "key_insights": ["Episodic, voice-captured thoughts provide higher signal than passive document indexing for long-horizon AI."],
        "thought_type": "idea",
        "urgency": "medium",
        "implicit_questions": ["How can episodic memory be modeled beyond basic RAG?", "What role does emotional state play in agent recall?"],
        "latitude": 37.4205,
        "longitude": -122.1830,
        "location_name": "Stanford Dish Trail, Palo Alto, CA"
    },
    {
        "created_at": "2026-07-18T18:30:00Z",
        "transcript": "Looking at our team sprint velocity... we're spending almost 15 hours a week in status syncs and fragmented meetings. Context switching is killing our deep work time. I think I'm going to propose 'No-Meeting Thursdays' to leadership next week to give the team dedicated flow blocks.",
        "summary": "Observing team burnout from meeting fragmentation and planning to propose a dedicated deep-work day.",
        "topics": ["team velocity", "workplace productivity", "deep work", "engineering culture"],
        "entities": ["Engineering Team", "Leadership"],
        "mood": "determined",
        "key_insights": ["Fragmented calendars are directly eroding engineering deep work blocks.", "Proposing a dedicated No-Meeting day could restore focus."],
        "thought_type": "decision",
        "urgency": "high",
        "implicit_questions": ["Will leadership support a dedicated No-Meeting day?", "How to measure focus time improvement?"],
        "latitude": 37.4323,
        "longitude": -122.0880,
        "location_name": "Shoreline Park, Mountain View, CA"
    },
    {
        "created_at": "2026-07-22T20:15:00Z",
        "transcript": "Mom called earlier about their 40th anniversary trip in August. They really want to see the California coast, but Mom doesn't do well with steep winding roads. Need to find a gentle scenic route down Highway 1 toward Monterey and Carmel with easy beach walks.",
        "summary": "Brainstorming family vacation itinerary for parents' upcoming 40th anniversary visit with accessible coastal walks.",
        "topics": ["family", "parents visit", "vacation planning", "California coast"],
        "entities": ["Mom", "Monterey", "Carmel", "Highway 1"],
        "mood": "warm",
        "key_insights": ["Plan gentle, non-mountainous coastal drives and accessible walking routes for parents."],
        "thought_type": "reflection",
        "urgency": "medium",
        "implicit_questions": ["What are the best gentle coastal trails in Monterey/Carmel?", "Where to book an ocean-view anniversary dinner?"],
        "latitude": 37.3941,
        "longitude": -122.0792,
        "location_name": "Castro St, Mountain View, CA"
    },
    {
        "created_at": "2026-07-27T12:45:00Z",
        "transcript": "While walking after lunch: on-device small models could do real-time voice structuring directly on a wearable or phone, and then asynchronously sync compact knowledge embeddings to the cloud. That solves both latency and privacy for continuous thought logging.",
        "summary": "Architecture idea for hybrid edge-cloud voice agents using on-device SLMs for local structuring and cloud embeddings for graph linking.",
        "topics": ["edge AI", "system architecture", "small language models", "privacy"],
        "entities": ["SLMs", "Wearables", "Cloud Sync"],
        "mood": "analytical",
        "key_insights": ["Hybrid architecture splits immediate voice structuring locally while offloading graph consolidation to cloud."],
        "thought_type": "idea",
        "urgency": "low",
        "implicit_questions": ["Can a 2B parameter model reliably output strict JSON on device?", "What is the battery impact on mobile?"],
        "latitude": 37.4210,
        "longitude": -122.0750,
        "location_name": "Charleston Park, Mountain View, CA"
    },
    {
        "created_at": "2026-08-01T09:15:00Z",
        "transcript": "Second weekend morning hike in a row. Noticed my resting heart rate is down and I haven't had that 3 PM brain fog this week. Morning movement before staring at screens makes a huge difference. I should make 30-minute morning walks non-negotiable.",
        "summary": "Realizing the direct correlation between morning walks in nature and reduced daily cognitive fatigue.",
        "topics": ["mindfulness", "health habits", "hiking", "wellbeing"],
        "entities": ["Rancho San Antonio"],
        "mood": "peaceful",
        "key_insights": ["Outdoor morning walks directly eliminate afternoon cognitive fatigue and improve focus."],
        "thought_type": "reflection",
        "urgency": "low",
        "implicit_questions": ["How can I protect morning walk time against early calendar invites?"],
        "latitude": 37.3325,
        "longitude": -122.0864,
        "location_name": "Rancho San Antonio, Cupertino, CA"
    },
    {
        "created_at": "2026-08-05T18:10:00Z",
        "transcript": "Had a great 1-on-1 with Alex today. They were hesitant to take ownership of the distributed caching service redesign. We mapped out milestone boundaries together and broke the risk down. Seeing junior engineers gain confidence is by far the most rewarding part of tech lead work.",
        "summary": "Mentoring reflection on empowering a junior engineer to lead a complex infrastructure redesign.",
        "topics": ["mentorship", "leadership", "engineering growth", "delegation"],
        "entities": ["Alex", "Caching Service"],
        "mood": "fulfilled",
        "key_insights": ["Scaffolding risk into smaller milestones enables junior engineers to step up to major architectural ownership."],
        "thought_type": "observation",
        "urgency": "low",
        "implicit_questions": ["How to set up the right review checkpoints without micro-managing?"],
        "latitude": 37.4180,
        "longitude": -122.0090,
        "location_name": "Baylands Park, Sunnyvale, CA"
    },
    {
        "created_at": "2026-08-09T19:20:00Z",
        "transcript": "Looking at the Golden Gate Bridge in the fog. Thought capture apps like AudioPen and Speakwise do transcription and bullet points, but they stop there. The killer product isn't a better notepad; it's a model that connects your idea from two weeks ago in Palo Alto to what you're thinking right now in SF.",
        "summary": "Crystalizing the vision for ThoughtStash — moving beyond simple voice transcription to an active cross-temporal pattern engine.",
        "topics": ["product vision", "ThoughtStash", "AI second brain", "pattern recognition"],
        "entities": ["ThoughtStash", "AudioPen", "Speakwise", "San Francisco"],
        "mood": "excited",
        "key_insights": ["The true differentiator for voice thought capture is temporal graph linking and proactive insight generation, not transcription formatting."],
        "thought_type": "idea",
        "urgency": "high",
        "implicit_questions": ["How to present connections without overwhelming the user?", "What is the optimal threshold for proactive alerts?"],
        "latitude": 37.8055,
        "longitude": -122.4650,
        "location_name": "Crissy Field, San Francisco, CA"
    },
    {
        "created_at": "2026-08-12T20:30:00Z",
        "transcript": "Showed my 10-year-old niece how we build games with Python and prompt helpers. Her eyes lit up when the sprite moved on the screen. She asked if computers can think about their own thoughts. Kids ask the most profound philosophical questions without even trying.",
        "summary": "Wholesome evening teaching niece basic programming and reflecting on her question about machine consciousness.",
        "topics": ["family", "niece", "STEM education", "philosophy"],
        "entities": ["Python", "Niece"],
        "mood": "joyful",
        "key_insights": ["Teaching kids coding sparks deep first-principles questions about artificial intelligence and introspection."],
        "thought_type": "observation",
        "urgency": "low",
        "implicit_questions": ["What is the best curriculum to introduce kids to computational thinking in the AI era?"],
        "latitude": 37.3775,
        "longitude": -122.0300,
        "location_name": "Historic Murphy Ave, Sunnyvale, CA"
    },
    {
        "created_at": "2026-08-15T11:30:00Z",
        "transcript": "Weekend walk along the ocean. Dad's 40th anniversary dinner reservations are confirmed in Carmel for next Saturday. Managed to completely unplug from Slack for 48 hours for the first time this quarter. The sky didn't fall, and my head feels completely clear.",
        "summary": "Finalizing parents' anniversary plans and experiencing the mental clarity of a full digital detox weekend.",
        "topics": ["digital detox", "family celebration", "ocean walk", "work life balance"],
        "entities": ["Dad", "Carmel", "Pacific Coast"],
        "mood": "rejuvenated",
        "key_insights": ["True digital detachment over weekends dramatically improves strategic problem-solving capacity on Monday."],
        "thought_type": "reflection",
        "urgency": "low",
        "implicit_questions": ["How to make 48-hour weekend disconnects a regular quarterly rhythm?"],
        "latitude": 36.9530,
        "longitude": -122.0320,
        "location_name": "West Cliff Drive, Santa Cruz, CA"
    },
    {
        "created_at": "2026-08-18T18:45:00Z",
        "transcript": "Two weeks into 'No-Meeting Thursdays' and team commit volume is up 35%, and code review turnaround dropped from 2 days to 4 hours. The engineers feel in control of their calendars again. Definite win to present in our end-of-month retro.",
        "summary": "Validating the success of No-Meeting Thursdays with concrete metrics on engineer velocity and review latency.",
        "topics": ["team velocity", "sprint metrics", "No-Meeting Thursdays", "process improvement"],
        "entities": ["Engineering Team", "Sprint Retro"],
        "mood": "proud",
        "key_insights": ["Consolidating meetings resulted in a measured 35% increase in engineering output and faster code reviews."],
        "thought_type": "decision",
        "urgency": "medium",
        "implicit_questions": ["Should we expand focus blocks to Tuesday mornings as well?"],
        "latitude": 37.2405,
        "longitude": -122.0320,
        "location_name": "Villa Montalvo Trail, Saratoga, CA"
    },
    {
        "created_at": "2026-08-20T07:15:00Z",
        "transcript": "Morning coffee walk before standup. If long-horizon agents have persistent state, they shouldn't just query memory reactively; they should have dream/consolidation phases during idle cycles, linking disparate memories into higher-order abstractions just like human REM sleep.",
        "summary": "Conceptualizing an autonomous background consolidation cycle for AI memory inspired by biological sleep and memory consolidation.",
        "topics": ["long-horizon agents", "memory consolidation", "agent sleep cycles", "neuro-AI"],
        "entities": ["Long-Horizon Agents", "REM Sleep Model"],
        "mood": "fascinated",
        "key_insights": ["Autonomous memory consolidation during agent idle periods mimics biological sleep and prevents knowledge fragmentation."],
        "thought_type": "idea",
        "urgency": "medium",
        "implicit_questions": ["How frequently should the agent run offline consolidation sweeps?", "What loss function measures abstraction quality?"],
        "latitude": 37.4445,
        "longitude": -122.1610,
        "location_name": "University Ave, Palo Alto, CA"
    },
    {
        "created_at": "2026-08-21T17:30:00Z",
        "transcript": "Walking along the Embarcadero after our offsite. The execs liked the agent architecture proposal, but asked how we prevent context bloat over 6-month horizons. Hierarchical summarization plus semantic clustering is the answer. Going to write a 1-pager on Sunday.",
        "summary": "Post-offsite reflection on solving multi-month context degradation in personal AI agents through hierarchical summarization.",
        "topics": ["offsite", "executive review", "context compression", "agent architecture"],
        "entities": ["Exec Team", "Embarcadero Offsite"],
        "mood": "focused",
        "key_insights": ["Hierarchical summarization paired with spatio-temporal clustering solves long-horizon agent context bloat."],
        "thought_type": "decision",
        "urgency": "high",
        "implicit_questions": ["What is the target compression ratio for 6-month thought timelines?"],
        "latitude": 37.7955,
        "longitude": -122.3937,
        "location_name": "Embarcadero, San Francisco, CA"
    },
    {
        "created_at": "2026-08-16T19:15:00Z",
        "transcript": "Manya's birthday party was so much fun, but it was way too crowded. I really wish I had invited a smaller number of people so it felt more relaxed.",
        "summary": "Reflecting on Manya's fun but overcrowded birthday party and wishing for a smaller, more intimate guest list.",
        "topics": ["family", "party planning", "Manya", "guest list", "event reflections"],
        "entities": ["Manya"],
        "mood": "reflective",
        "key_insights": ["Smaller guest lists at children's parties allow for more relaxed, high-quality interactions."],
        "thought_type": "reflection",
        "urgency": "medium",
        "implicit_questions": ["What is the ideal guest count for a kids' birthday party?"],
        "latitude": 37.3195,
        "longitude": -122.0435,
        "location_name": "Memorial Park, Cupertino, CA"
    },
    {
        "created_at": "2026-08-22T16:30:00Z",
        "transcript": "Today's party was awesome, really loved the piñata! Next time I should definitely get that for Ananya's birthday party.",
        "summary": "Enjoyed today's party and decided to get a piñata for Ananya's upcoming birthday party.",
        "topics": ["family", "party planning", "Ananya", "birthday ideas", "piñata"],
        "entities": ["Ananya", "Piñata"],
        "mood": "joyful",
        "key_insights": ["Piñatas are a massive hit for kids' celebrations and will be great for Ananya."],
        "thought_type": "decision",
        "urgency": "medium",
        "implicit_questions": ["Where to buy a custom piñata?", "Which outdoor park venue is best for hanging a piñata?"],
        "latitude": 37.3755,
        "longitude": -122.0620,
        "location_name": "Cuesta Park, Mountain View, CA"
    },
    {
        "created_at": "2026-07-03T08:30:00Z",
        "transcript": "If we evaluate agent reasoning purely on single-turn benchmarks, we miss 90% of real-world failures. An agent that drifts in belief after 10 conversation turns is far worse than one that makes a single predictable syntax error. We need multi-day evaluation suites that measure conviction drift and memory decay.",
        "summary": "Proposing multi-day benchmark evaluations for personal agents to measure belief drift and long-term memory consistency.",
        "topics": ["AI agents", "benchmarking", "memory decay", "eval drift", "agent evaluation"],
        "entities": ["Single-Turn Benchmarks", "Long-Term Memory"],
        "mood": "analytical",
        "key_insights": ["Multi-turn conviction drift is the primary failure mode of long-horizon AI agents."],
        "thought_type": "idea",
        "urgency": "medium",
        "implicit_questions": ["What metrics quantify multi-day belief stability?", "How to automate multi-turn regression testing?"],
        "latitude": 37.4300,
        "longitude": -122.1697,
        "location_name": "Stanford Oval, Palo Alto, CA"
    },
    {
        "created_at": "2026-07-08T17:15:00Z",
        "transcript": "Sitting on the grass watching people: voice interactions with AI feel awkward when there's an unnatural pause. If an on-device model can stream back subtle acoustic acknowledgments — an affirmative mhm or brief pause cadence — while the cloud processes the heavy context, it transforms the entire conversational dynamic.",
        "summary": "Exploring acoustic micro-acknowledgments and low-latency audio streaming to make voice thought capture feel natural and conversational.",
        "topics": ["voice UX", "audio streaming", "latency", "human-computer interaction"],
        "entities": ["On-Device Models", "Voice UX"],
        "mood": "inspired",
        "key_insights": ["Low-latency acoustic acknowledgments bridge network roundtrip latency and preserve conversational flow."],
        "thought_type": "idea",
        "urgency": "medium",
        "implicit_questions": ["What is the optimal latency threshold for audio filler tokens?"],
        "latitude": 37.7596,
        "longitude": -122.4269,
        "location_name": "Mission Dolores Park, San Francisco, CA"
    },
    {
        "created_at": "2026-07-16T12:20:00Z",
        "transcript": "RAG with raw vector search retrieves matching keywords, but it has no sense of time or causal progression. When I ask 'how has my view on remote work changed?', cosine similarity on text chunks returns static snapshots. We need chronological graph traversals with temporal decay weights.",
        "summary": "Identifying the temporal limitations of naive RAG and designing chronological graph traversal for evolving ideas.",
        "topics": ["RAG", "graph traversal", "temporal embeddings", "semantic search", "AI memory"],
        "entities": ["Naive RAG", "Temporal Graphs"],
        "mood": "focused",
        "key_insights": ["Temporal decay weights combined with semantic similarity capture the trajectory of evolving human perspectives."],
        "thought_type": "reflection",
        "urgency": "high",
        "implicit_questions": ["How should temporal decay curves be parameterized for thought graphs?"],
        "latitude": 37.5368,
        "longitude": -122.2514,
        "location_name": "Redwood Shores Trail, Redwood City, CA"
    },
    {
        "created_at": "2026-07-25T16:45:00Z",
        "transcript": "The fog rolling over the Pacific reminds me of distributed systems consistency. When multiple specialized agents collaborate on a user's stash — one extracting facts, one synthesizing themes, one validating privacy — they need an append-only event log rather than mutable shared state to prevent race conditions.",
        "summary": "Architectural realization that multi-agent memory synthesis requires append-only event logs to ensure strict consistency.",
        "topics": ["multi-agent", "event sourcing", "distributed systems", "system architecture"],
        "entities": ["Event Sourcing", "Multi-Agent Systems"],
        "mood": "analytical",
        "key_insights": ["Append-only immutable event logs prevent state corruption across asynchronous agent workers."],
        "thought_type": "decision",
        "urgency": "high",
        "implicit_questions": ["What is the compaction strategy for long-running agent event logs?"],
        "latitude": 37.7844,
        "longitude": -122.5059,
        "location_name": "Lands End Trail, San Francisco, CA"
    },
    {
        "created_at": "2026-08-03T08:10:00Z",
        "transcript": "Why do we discard raw acoustic features during transcription? A sentence spoken with hesitation or excitement conveys completely different intent. Storing acoustic prosody tags alongside text embeddings would allow the model to query for 'ideas I sounded really passionate about last month'.",
        "summary": "Suggesting the retention of acoustic prosody and vocal sentiment tags to allow emotional querying across past voice notes.",
        "topics": ["audio processing", "prosody", "multimodal AI", "voice embeddings"],
        "entities": ["Acoustic Prosody", "Speech Emotion"],
        "mood": "excited",
        "key_insights": ["Vocal cadence and acoustic energy provide essential emotional context lost in plain text transcription."],
        "thought_type": "idea",
        "urgency": "medium",
        "implicit_questions": ["Which compact audio features best represent vocal enthusiasm without ballooning storage?"],
        "latitude": 37.4080,
        "longitude": -122.1480,
        "location_name": "Page Mill Road, Palo Alto, CA"
    },
    {
        "created_at": "2026-08-07T18:00:00Z",
        "transcript": "Testing synthetic data generation for our connector agent. If you train the model purely on synthetic conversations, it develops unnatural verbosity and boilerplate. Filtering for concise, punchy human reasoning makes the graph connections 10x crisper.",
        "summary": "Discovering that filtering synthetic data for human brevity prevents verbose hallucinations in agent memory linking.",
        "topics": ["synthetic data", "model fine-tuning", "agent prompting", "concise reasoning"],
        "entities": ["Synthetic Data", "Connector Agent"],
        "mood": "satisfied",
        "key_insights": ["Human-like brevity filters eliminate boilerplate sycophancy in LLM memory synthesis."],
        "thought_type": "observation",
        "urgency": "low",
        "implicit_questions": ["What automated heuristic best flags sycophantic language in synthetic datasets?"],
        "latitude": 37.8018,
        "longitude": -122.4587,
        "location_name": "Presidio Tunnel Tops, San Francisco, CA"
    },
    {
        "created_at": "2026-08-14T11:40:00Z",
        "transcript": "Reviewing our vector index memory footprint. Quantizing 768-dimensional embeddings to 8-bit integers reduced RAM usage by 75% with zero measurable loss in top-8 retrieval recall. This makes running the entire memory graph on mobile completely viable.",
        "summary": "Achieving a 75% memory reduction in the vector index through 8-bit quantization without losing retrieval accuracy.",
        "topics": ["quantization", "vector search", "performance optimization", "mobile deployment"],
        "entities": ["Vector Quantization", "Mobile Memory"],
        "mood": "victorious",
        "key_insights": ["Int8 scalar quantization slashes vector RAM footprint by 4x while preserving semantic nearest-neighbor ordering."],
        "thought_type": "decision",
        "urgency": "medium",
        "implicit_questions": ["Is product quantization worth the extra decode latency on ARM chips?"],
        "latitude": 37.4492,
        "longitude": -122.1963,
        "location_name": "Allied Arts Guild, Menlo Park, CA"
    },
    {
        "created_at": "2026-08-22T08:00:00Z",
        "transcript": "Early morning by the bay. The real magic of an AI second brain isn't search; it's serendipity. It's when you're preparing for a product review and the agent proactively reminds you of a sketch you muttered while stuck in traffic three weeks ago.",
        "summary": "Reflecting on proactive serendipity as the defining characteristic of a true cognitive second brain.",
        "topics": ["second brain", "proactive AI", "serendipity", "product design"],
        "entities": ["Second Brain", "ThoughtStash Vision"],
        "mood": "inspired",
        "key_insights": ["Passive search requires user intent; proactive memory synthesis delivers serendipitous cognitive leaps."],
        "thought_type": "reflection",
        "urgency": "low",
        "implicit_questions": ["How do we calibrate proactive recall notifications to prevent alert fatigue?"],
        "latitude": 37.7955,
        "longitude": -122.3937,
        "location_name": "Ferry Building Plaza, San Francisco, CA"
    },
    {
        "created_at": "2026-07-05T10:15:00Z",
        "transcript": "We're trying to build three major features at once and none are hitting quality bars. Decided to pause the experimental plugin system and concentrate all engineering capacity on voice latency and graph connection accuracy. Doing two things exceptionally beats five things moderately.",
        "summary": "Making the executive call to ruthless prioritize core voice latency and graph accuracy over peripheral plugins.",
        "topics": ["product strategy", "prioritization", "engineering focus", "quality"],
        "entities": ["Engineering Team", "Q3 Roadmap"],
        "mood": "resolute",
        "key_insights": ["Narrowing focus to core latency and graph reliability creates defensible product excellence."],
        "thought_type": "decision",
        "urgency": "high",
        "implicit_questions": ["How to communicate feature pauses to external stakeholders without losing momentum?"],
        "latitude": 37.4115,
        "longitude": -122.0538,
        "location_name": "Moffett Park, Mountain View, CA"
    },
    {
        "created_at": "2026-07-11T14:30:00Z",
        "transcript": "Coffee with Maya from the data infra team. Cross-functional friction is almost always an information symmetry problem, not a personality clash. Setting up shared weekly dashboard snapshots will align our roadmap expectations without extra meetings.",
        "summary": "Resolving cross-team engineering friction by establishing asynchronous dashboard visibility instead of sync meetings.",
        "topics": ["cross-functional", "engineering leadership", "communication", "org design"],
        "entities": ["Data Infra Team", "Maya"],
        "mood": "thoughtful",
        "key_insights": ["Asynchronous data transparency removes organizational friction better than recurring alignment meetings."],
        "thought_type": "observation",
        "urgency": "medium",
        "implicit_questions": ["Which metrics best reflect real inter-team dependencies?"],
        "latitude": 37.2215,
        "longitude": -121.9847,
        "location_name": "Downtown Los Gatos Plaza, Los Gatos, CA"
    },
    {
        "created_at": "2026-07-19T17:45:00Z",
        "transcript": "Our senior engineers are spending 40% of their time reviewing boilerplate PRs. If we automate style and basic lint feedback with pre-commit agent checks, senior reviewers can focus purely on architecture and concurrency risks.",
        "summary": "Planning to automate routine PR feedback so senior engineers can focus review bandwidth on architecture and security.",
        "topics": ["code review", "automation", "developer productivity", "engineering culture"],
        "entities": ["Code Review System", "Senior Engineers"],
        "mood": "determined",
        "key_insights": ["Automating mechanical code review tasks frees senior engineering bandwidth for high-leverage architectural review."],
        "thought_type": "decision",
        "urgency": "medium",
        "implicit_questions": ["What threshold of automated linting avoids false-positive friction for developers?"],
        "latitude": 37.3892,
        "longitude": -122.0673,
        "location_name": "Stevens Creek Trail, Mountain View, CA"
    },
    {
        "created_at": "2026-07-29T07:50:00Z",
        "transcript": "Quiet morning walk along Canada Road. We had a minor outage yesterday because of an unhandled timeout in our external geocoding service. Wrote down a resilient circuit-breaker policy: fall back to cached city bounding boxes instantly if latency exceeds 200ms.",
        "summary": "Formulating a strict circuit-breaker and caching fallback policy for external API dependencies following an outage.",
        "topics": ["reliability", "circuit breaker", "system resilience", "post-mortem"],
        "entities": ["Geocoding API", "Circuit Breaker"],
        "mood": "focused",
        "key_insights": ["Graceful degradation with local cached geo-bounding boxes prevents third-party API outages from affecting user experience."],
        "thought_type": "decision",
        "urgency": "high",
        "implicit_questions": ["What is the optimal TTL for city boundary cache entries?"],
        "latitude": 37.4827,
        "longitude": -122.3082,
        "location_name": "Pulgas Water Temple, Redwood City, CA"
    },
    {
        "created_at": "2026-08-04T12:15:00Z",
        "transcript": "Finished reviewing the Q3 OKR drafts. The teams that set 3 audacious goals with crisp binary deliverables are moving with twice the confidence of the teams that have 12 vague aspirational bullets. Simplicity in strategy creates speed.",
        "summary": "Observing that concise, binary OKRs dramatically increase execution speed compared to long aspirational lists.",
        "topics": ["OKRs", "goal setting", "execution velocity", "strategy"],
        "entities": ["Q3 OKRs", "Leadership Team"],
        "mood": "confident",
        "key_insights": ["Fewer, high-conviction binary goals eliminate prioritization ambiguity across engineering teams."],
        "thought_type": "observation",
        "urgency": "low",
        "implicit_questions": ["How do we teach junior tech leads to write binary, testable key results?"],
        "latitude": 37.4470,
        "longitude": -122.1600,
        "location_name": "Lytton Plaza, Palo Alto, CA"
    },
    {
        "created_at": "2026-08-10T19:00:00Z",
        "transcript": "Interviewed a great principal engineer candidate today. The best technical leaders don't just solve hard problems; they articulate trade-offs in plain language that junior devs and product managers alike understand. Updating our interview rubric to weight communication clarity equally with systems design.",
        "summary": "Updating engineering interview criteria to prioritize clear trade-off articulation alongside deep systems design.",
        "topics": ["hiring", "interview rubric", "technical leadership", "communication"],
        "entities": ["Interview Panel", "Principal Engineer Candidate"],
        "mood": "energized",
        "key_insights": ["The ability to demystify complex architectural trade-offs is the highest predictor of senior engineering leadership impact."],
        "thought_type": "decision",
        "urgency": "medium",
        "implicit_questions": ["How can our interview questions better evaluate empathy and mentorship aptitude?"],
        "latitude": 37.3218,
        "longitude": -121.9478,
        "location_name": "Santana Row, San Jose, CA"
    },
    {
        "created_at": "2026-08-17T08:40:00Z",
        "transcript": "Walking near Boronda Lake. Deprecating v1 of our public API is going to take 6 months if we wait for legacy clients to voluntarily migrate. Proposing a sunset schedule with scheduled brownouts starting in September so teams actually test the new endpoints.",
        "summary": "Outlining a scheduled brownout strategy to accelerate legacy API client migration to v2.",
        "topics": ["API deprecation", "migration strategy", "infrastructure", "release management"],
        "entities": ["Public API v1", "Deprecation Schedule"],
        "mood": "resolute",
        "key_insights": ["Controlled progressive brownouts force client discovery of legacy API dependencies before hard shutdowns."],
        "thought_type": "decision",
        "urgency": "high",
        "implicit_questions": ["What duration of initial brownout window gives clients enough signal without breaking production workflows?"],
        "latitude": 37.3550,
        "longitude": -122.1800,
        "location_name": "Foothills Park, Palo Alto, CA"
    },
    {
        "created_at": "2026-08-21T18:50:00Z",
        "transcript": "Reflecting on our sprint retrospective. When team morale drops, it's rarely about the workload itself; it's about not seeing the tangible impact of their code on real users. We should share real customer walk-recordings at every bi-weekly demo.",
        "summary": "Connecting engineering team motivation directly to user impact and establishing user story demos in sprint retros.",
        "topics": ["team morale", "engineering culture", "user impact", "sprint retro"],
        "entities": ["Sprint Retrospective", "User Research"],
        "mood": "motivated",
        "key_insights": ["Direct exposure to authentic user feedback restores engineering purpose faster than any process tweak."],
        "thought_type": "reflection",
        "urgency": "low",
        "implicit_questions": ["How can we ethically share anonymized user voice snippets during internal sprint demos?"],
        "latitude": 37.7715,
        "longitude": -122.3900,
        "location_name": "Mission Bay Park, San Francisco, CA"
    },
    {
        "created_at": "2026-07-02T09:30:00Z",
        "transcript": "Sunday morning farmers market with family. Got fresh heirloom peaches and sourdough. Need to remember that Mom loves lavender honey — pick up two jars before her anniversary visit next month.",
        "summary": "Enjoying a Sunday morning farmers market with family and noting down lavender honey as a gift for Mom's anniversary trip.",
        "topics": ["family", "farmers market", "gifts", "Mom", "anniversary prep"],
        "entities": ["Farmers Market", "Mom", "Lavender Honey"],
        "mood": "warm",
        "key_insights": ["Small, thoughtful personal gestures like local specialty honey make anniversary visits memorable."],
        "thought_type": "observation",
        "urgency": "low",
        "implicit_questions": ["Which local market stand has authentic Carmel Valley lavender honey?"],
        "latitude": 37.3945,
        "longitude": -122.0780,
        "location_name": "Mountain View Farmers Market, Mountain View, CA"
    },
    {
        "created_at": "2026-07-09T18:15:00Z",
        "transcript": "Kayaking with my brother. We talked through the anniversary slide deck we're making for Mom and Dad's 40th. Found childhood photos from our road trip to Yellowstone in 1998. It's going to make Dad tear up for sure.",
        "summary": "Brainstorming the 40th anniversary family photo slideshow and finding nostalgic childhood road trip pictures.",
        "topics": ["family", "anniversary slideshow", "childhood memories", "brother"],
        "entities": ["Brother", "Mom & Dad", "Yellowstone Slideshow"],
        "mood": "joyful",
        "key_insights": ["Curating shared family milestones across decades creates deep emotional resonance for milestone anniversaries."],
        "thought_type": "reflection",
        "urgency": "medium",
        "implicit_questions": ["How can we digitize old 35mm photo slides with high dynamic range before next month?"],
        "latitude": 37.4320,
        "longitude": -122.0910,
        "location_name": "Shoreline Lake Boathouse, Mountain View, CA"
    },
    {
        "created_at": "2026-07-20T16:00:00Z",
        "transcript": "Looking at customized handcrafted jewelry on Main Street. Found a beautiful dual-stone pendant for Mom representing 40 years together. Going to order it engraved with their wedding date: August 28, 1986.",
        "summary": "Selecting an engraved dual-stone commemorative pendant for Mom's 40th anniversary milestone gift.",
        "topics": ["family", "anniversary gift", "Mom", "celebration"],
        "entities": ["Mom", "Anniversary Pendant", "Main Street Jewelers"],
        "mood": "happy",
        "key_insights": ["Commemorative jewelry engraved with key milestones carries enduring sentimental value."],
        "thought_type": "decision",
        "urgency": "medium",
        "implicit_questions": ["What is the production turnaround time for custom jewel engraving?"],
        "latitude": 37.3790,
        "longitude": -122.1180,
        "location_name": "Downtown Los Altos Main St, Los Altos, CA"
    },
    {
        "created_at": "2026-07-31T19:30:00Z",
        "transcript": "Sunset walk past the colorful Venetian cottages. The beach breeze is calm. This would be a perfect spot to bring Mom and Dad for lunch after the Carmel drive. Flat, paved boardwalk right next to the sand.",
        "summary": "Scouting Capitola Beach's flat, paved boardwalk as an ideal accessible coastal lunch spot for parents' visit.",
        "topics": ["family visit", "itinerary planning", "Capitola", "accessible walks"],
        "entities": ["Capitola Beach", "Venetian Cottages", "Parents"],
        "mood": "peaceful",
        "key_insights": ["Paved seaside promenades accommodate varying mobility levels without sacrificing coastal views."],
        "thought_type": "observation",
        "urgency": "low",
        "implicit_questions": ["Which oceanside cafe in Capitola accepts lunch reservations for groups?"],
        "latitude": 36.9720,
        "longitude": -121.9530,
        "location_name": "Capitola Venetian Beach, Capitola, CA"
    },
    {
        "created_at": "2026-08-08T10:45:00Z",
        "transcript": "Walking through the Japanese koi ponds at Hakone Gardens. The bamboo groves and stone lanterns create such an incredible stillness. Definitely booking morning tickets for Mom and Dad during their visit — it's gentle, shaded, and stunning.",
        "summary": "Touring Hakone Gardens and deciding to book morning tickets for parents' anniversary visit due to gentle, shaded paths.",
        "topics": ["family visit", "Hakone Gardens", "vacation itinerary", "parents"],
        "entities": ["Hakone Gardens", "Parents Vacation"],
        "mood": "serene",
        "key_insights": ["Shaded garden strolls offer a restorative midday pause during multi-day sightseeing itineraries."],
        "thought_type": "decision",
        "urgency": "medium",
        "implicit_questions": ["Is motorized cart transport available on site if walking becomes tiring?"],
        "latitude": 37.2540,
        "longitude": -122.0360,
        "location_name": "Hakone Gardens, Saratoga, CA"
    },
    {
        "created_at": "2026-08-16T14:30:00Z",
        "transcript": "Helped Ananya build a miniature cardboard treehouse today. She insisted on making a tiny hammock for her toy squirrel out of dental floss. Kids have an endless imagination when you give them simple materials without screens.",
        "summary": "Spending creative weekend time with Ananya building a cardboard treehouse and observing the power of imaginative offline play.",
        "topics": ["family", "Ananya", "crafts", "unplugged play", "weekend"],
        "entities": ["Ananya", "Cardboard Crafts"],
        "mood": "joyful",
        "key_insights": ["Tactile, unplugged building activities foster deeper creative focus in young children than digital apps."],
        "thought_type": "reflection",
        "urgency": "low",
        "implicit_questions": ["What other hands-on engineering craft kits would Ananya enjoy for her birthday?"],
        "latitude": 37.5615,
        "longitude": -122.3215,
        "location_name": "Central Park, San Mateo, CA"
    },
    {
        "created_at": "2026-08-22T18:15:00Z",
        "transcript": "Picked up fresh artichoke bread and walked the coastal bluff. The ocean fog cleared just as the sun set. Everything for Mom and Dad's arrival next week is booked — Carmel hotel, Capitola lunch, and the anniversary dinner at Pacific's Edge. Feeling deeply grateful.",
        "summary": "Finalizing all logistics for parents' 40th anniversary trip and taking a sunset walk along Half Moon Bay bluffs.",
        "topics": ["family celebration", "40th anniversary", "Half Moon Bay", "gratitude"],
        "entities": ["Mom & Dad", "Pacific's Edge Carmel", "Half Moon Bay"],
        "mood": "grateful",
        "key_insights": ["Completing milestone trip planning well in advance creates space for calm, fully present presence with family."],
        "thought_type": "reflection",
        "urgency": "low",
        "implicit_questions": ["What is the backup indoor plan if coastal fog rolls in heavy on dinner night?"],
        "latitude": 37.4635,
        "longitude": -122.4410,
        "location_name": "Half Moon Bay Coastal Trail, Half Moon Bay, CA"
    },
    {
        "created_at": "2026-07-06T07:15:00Z",
        "transcript": "Early morning eucalyptus trail. Cold air in my lungs. I've realized that my best architectural solutions never come when I'm staring at a blank IDE file. They happen at mile 2 of a trail when the conscious mind steps out of the way.",
        "summary": "Realizing that creative problem-solving and systems architecture insights emerge naturally during outdoor movement.",
        "topics": ["mindfulness", "hiking", "creativity", "nature", "neuroscience"],
        "entities": ["Tilden Park", "Subconscious Processing"],
        "mood": "inspired",
        "key_insights": ["Rhythmic physical movement in nature disengages executive cognitive control and unlocks diffuse-mode problem solving."],
        "thought_type": "reflection",
        "urgency": "low",
        "implicit_questions": ["How can I systematically structure walk breaks during high-complexity engineering sprints?"],
        "latitude": 37.8960,
        "longitude": -122.2530,
        "location_name": "Tilden Regional Park, Berkeley, CA"
    },
    {
        "created_at": "2026-07-13T18:40:00Z",
        "transcript": "Windy hike up the stairs to the cliff edge. Watching the waves crash against the rock. Decided to cut afternoon caffeine after 1 PM. Let's see if my sleep latency drops from 40 minutes down to 15 this week.",
        "summary": "Committing to a strict 1 PM caffeine cutoff to improve sleep latency and nighttime recovery.",
        "topics": ["health habits", "sleep quality", "caffeine", "wellness"],
        "entities": ["Sleep Latency", "Caffeine Half-Life"],
        "mood": "determined",
        "key_insights": ["Halting caffeine consumption 9 hours before bedtime preserves deep sleep architecture and shortens sleep latency."],
        "thought_type": "decision",
        "urgency": "medium",
        "implicit_questions": ["What herbal teas provide an afternoon sensory ritual without the caffeine spike?"],
        "latitude": 37.6045,
        "longitude": -122.4975,
        "location_name": "Mori Point, Pacifica, CA"
    },
    {
        "created_at": "2026-07-24T17:30:00Z",
        "transcript": "Biking along Alpine Road past the horse pastures. Experimented with 2-minute physiological sigh breathing when feeling overwhelmed before my executive demo today. Heart rate settled within 60 seconds. Breathwork is a legit superpower.",
        "summary": "Validating physiological sigh breathwork for immediate nervous system down-regulation before high-stakes presentations.",
        "topics": ["breathwork", "stress management", "mindfulness", "performance"],
        "entities": ["Physiological Sigh", "Nervous System"],
        "mood": "calm",
        "key_insights": ["Double inhalation followed by extended exhalation activates parasympathetic braking and rapidly reduces acute stress."],
        "thought_type": "observation",
        "urgency": "low",
        "implicit_questions": ["Can wearable biofeedback triggers detect stress spikes and prompt breathwork micro-sessions?"],
        "latitude": 37.3710,
        "longitude": -122.2220,
        "location_name": "Alpine Trail, Portola Valley, CA"
    },
    {
        "created_at": "2026-08-02T08:50:00Z",
        "transcript": "Trail run in the oak foothills. Tracked my weekly step average — hit 14,000 steps per day for July, up from 7,500 in May. Energy levels throughout the working day are completely steady, no more afternoon crashes.",
        "summary": "Celebrating a milestone of 14,000 daily steps in July and noting sustained day-long energy and mental stamina.",
        "topics": ["fitness metrics", "step goal", "trail running", "energy levels"],
        "entities": ["Daily Step Goal", "Almaden Quicksilver"],
        "mood": "energized",
        "key_insights": ["Doubling daily baseline movement stabilizes blood glucose and completely eliminates afternoon energy troughs."],
        "thought_type": "reflection",
        "urgency": "low",
        "implicit_questions": ["What is the sustainable winter daily step target when daylight hours decrease?"],
        "latitude": 37.1820,
        "longitude": -121.8310,
        "location_name": "Almaden Quicksilver County Park, San Jose, CA"
    },
    {
        "created_at": "2026-08-11T19:15:00Z",
        "transcript": "Shaded redwood trail after morning rain. The smell of cedar and damp earth is unmatched. Replaced my evening phone scrolling with 20 minutes of reading physical books this week, and my Oura sleep score jumped 8 points.",
        "summary": "Replacing late-night phone screens with physical books and observing an immediate 8-point boost in sleep quality.",
        "topics": ["sleep hygiene", "screen time", "reading", "recovery", "wellbeing"],
        "entities": ["Oura Sleep Score", "Screenless Evening"],
        "mood": "peaceful",
        "key_insights": ["Eliminating blue light emission and interactive algorithmic stimuli 45 minutes before sleep significantly enhances REM cycles."],
        "thought_type": "observation",
        "urgency": "low",
        "implicit_questions": ["What fiction genres are most conducive to relaxing cognitive pre-sleep wind-down?"],
        "latitude": 37.4290,
        "longitude": -122.2535,
        "location_name": "Town Center Trail, Woodside, CA"
    },
    {
        "created_at": "2026-08-17T15:30:00Z",
        "transcript": "Full day hike in the old-growth Douglas firs. No cell signal for 6 hours. When you remove the constant notification hum, thoughts expand and deepen. You stop reacting to minute-by-minute crises and start contemplating year-long horizons.",
        "summary": "Experiencing the expansive cognitive benefits of complete offline stillness during an all-day Point Reyes hike.",
        "topics": ["solitude", "Point Reyes", "deep thinking", "digital detox", "nature"],
        "entities": ["Point Reyes National Seashore", "Long-Horizon Thinking"],
        "mood": "serene",
        "key_insights": ["Extended periods of zero digital connectivity restore long-horizon strategic cognition and emotional balance."],
        "thought_type": "reflection",
        "urgency": "low",
        "implicit_questions": ["How can leaders model regular offline solitude days without blocking team operational velocity?"],
        "latitude": 38.0410,
        "longitude": -122.7990,
        "location_name": "Bear Valley Trail, Point Reyes, CA"
    },
    {
        "created_at": "2026-08-22T19:40:00Z",
        "transcript": "Walking by the water at dusk watching the pelicans. Hydration challenge week 3: drinking 3 liters of water every day has completely eliminated my afternoon tension headaches. Simple physiological habits outperform complex productivity hacks every single time.",
        "summary": "Confirming that consistent daily hydration eliminated afternoon tension headaches and boosted baseline focus.",
        "topics": ["hydration habits", "health habits", "daily wellness", "Shoreline Lake"],
        "entities": ["Hydration Protocol", "Shoreline Lake"],
        "mood": "content",
        "key_insights": ["Consistent daily water intake directly prevents vascular tension headaches and sharpens working memory."],
        "thought_type": "observation",
        "urgency": "low",
        "implicit_questions": ["What is the easiest reminder trigger to pace water consumption evenly across working hours?"],
        "latitude": 37.4280,
        "longitude": -122.0830,
        "location_name": "Shoreline Lake Park, Mountain View, CA"
    }
]


async def seed_data():
    print("🌱 Initializing DB...")
    db.init_db()

    print(f"🧠 Generating real Gemini embeddings for {len(DEMO_THOUGHTS)} sample thoughts...")
    for idx, item in enumerate(DEMO_THOUGHTS, 1):
        print(f"[{idx}/{len(DEMO_THOUGHTS)}] Embedding: {item['summary'][:50]}...")
        try:
            emb = agents.get_embedding(item["transcript"])
        except Exception as e:
            print(f"   Embedding error: {e}, using empty list")
            emb = []

        thought_record = {
            "created_at": item["created_at"],
            "audio_path": None,
            "transcript": item["transcript"],
            "summary": item["summary"],
            "topics": item["topics"],
            "entities": item["entities"],
            "mood": item["mood"],
            "key_insights": item["key_insights"],
            "thought_type": item["thought_type"],
            "urgency": item["urgency"],
            "implicit_questions": item["implicit_questions"],
            "latitude": item["latitude"],
            "longitude": item["longitude"],
            "location_name": item["location_name"],
            "embedding": emb,
            "raw_response": json.dumps(item),
        }
        t_id = db.save_thought(thought_record)
        print(f"   Saved thought #{t_id} ({item['location_name']})")

    print("\n✨ Generating Connector agent pattern links for thoughts...")
    all_thoughts = db.get_all_thoughts()
    
    # Run connector on a subset of thoughts to populate realistic connections
    for i in range(1, min(len(all_thoughts), 6)):
        target = all_thoughts[i]
        past = all_thoughts[i+1:]
        if past:
            try:
                print(f"🔗 Linking thought #{target['id']} against {len(past)} historical thoughts...")
                analysis = await agents.connector_analyze(target, past[:10])
                db.update_thought_connections(target["id"], json.dumps(analysis))
            except Exception as e:
                print(f"   Connector error on #{target['id']}: {e}")

    print(f"\n🎉 Successfully seeded {len(DEMO_THOUGHTS)} Bay Area demo thoughts across Tech, Work, and Family!")


if __name__ == "__main__":
    asyncio.run(seed_data())
